#!/usr/bin/bash

#PBS -l select=1:ncpus=6:mpiprocs=6:mem=32gb
#PBS -l walltime=00:15:0
#PBS -N testName

### make sure no other modules are loaded

module purge

### Load modules for the needed application (if already installed on the HPC)
### module load git

### Change directory to the submission folder (where my script is located in this example)

cd ${PBS_O_WORKDIR}

### Run wget against the URL_list.txt

